id: IC24AC133
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T16:08:47+00:00'
last_modified: '2022-06-09T07:29:21.604169+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3642
  title: འདུལ་བའི་ལག་ལེན་གྱི་ཆོ་ག་དྲི་མ་མེད་པའི་ཕྲེང་བ་སོགས་ཆོས་ཚན་ཁག་ཅིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    98CB:
      image_group_id: I1KG3649
      title: Volume 1 of 'dul ba'i lag len gyi cho ga dri ma med pa'i phreng ba sogs
        chos tshan khag cig
      total_pages: 672
      order: 1
      base_file: 98CB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
