id: P007918
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3642
  title: འདུལ་བའི་ལག་ལེན་གྱི་ཆོ་ག་དྲི་མ་མེད་པའི་ཕྲེང་བ་སོགས་ཆོས་ཚན་ཁག་ཅིག
  author: ''
  volumes:
    4f82cc21326e497fb104a602cb4cb424:
      image_group_id: I1KG3649
      title: ''
      volume_number: 1
      total_pages: 672
ebook_metadata:
  title: འདུལ་བའི་ལག་ལེན་གྱི་ཆོ་ག་དྲི་མ་མེད་པའི་ཕྲེང་བ་སོགས་ཆོས་ཚན་ཁག་ཅིག
  author: ''
  sku: P007918
  cover: cover.jpg
  layers:
  - pagination
